added "transformation type" option

diff --git a/main b/main
--- a/main
+++ b/main
@@ -15,9 +15,57 @@ lmax=$(jq -r .lmax config.json)
 fod=$(jq -r '.lmax'"${lmax}" config.json)
 fa_moving=$(jq -r .fa config.json)
 fa_fixed=$(jq -r .fa_fixed config.json)
+transf_type=$(jq -r .transformation config.json)
 settings=$(jq -r .settings config.json)
 
 ### === Set ANTs registration parameters ===
+
+case $transf_type in
+  "translation")
+    echo "Performing rigid registration"
+
+    transl=1
+    rigid=0
+    affine=0
+    nonlin=0
+
+    ;;
+  "rigid")
+    echo "Performing rigid registration"
+
+    transl=1
+    rigid=1
+    affine=0
+    nonlin=0
+
+    ;;
+  "rigid")
+    echo "Performing rigid registration"
+
+    transl=1
+    rigid=1
+    affine=1
+    nonlin=0
+    ;;
+  "rigid")
+    echo "Performing rigid registration"
+    
+    transl=1
+    rigid=1
+    affine=1
+    nonlin=1
+    ;;
+  *)
+    echo "Invalid trasnformation type"
+    exit 1
+    ;;
+esac
+
+
+#default params
+thresold=1.e-8
+diffeo="SyN[0.25]"
+
 case $settings in
   "1")
     echo "Using one-level registration"
@@ -43,15 +91,29 @@ case $settings in
   "4")
     echo "Using four-level registration"
     its="10000x10000x10000"
-    syn="100x80x50x20,-0.01,10"
+    syn="100x80x50x20,${thresold},10"
     sigma="2x1x0.5x0vox"
     shrink="8x4x2x1"
+    sigma_lin=4x2x1vox
+    shrink0=6x4x2
+    shrink_lin=3x2x1
     ;;
   *)
     echo "Invalid registration setting"
     exit 1
     ;;
 esac
+
+
+stage0="-m mattes[  $f, $m , 1 , 32, regular, $percentage ] -t translation[ 0.1 ] -c [$its,$thresold,20] -u 1 -s $shrink_lin -f $shrink0 -l 1"
+tage1="-m mattes[  $f, $m , 1 , 32, regular, $percentage ] -t rigid[ 0.1 ]       -c [$its,$thresold,20] -u 1 -s $shrink_lin -f $shrink_lin -l 1"
+stage2="-m mattes[  $f, $m , 1 , 32, regular, $percentage ] -t affine[ 0.1 ]      -c [$its,$thresold,20] -u 1 -s $shrink_lin -f $shrink_lin -l 1"
+stage3="-m mattes[  $f, $m , 0.5 , 32 ] -m cc[  $f, $m , 0.5 , 4 ]   -c [ $syn ]  -t $diffeo -s $sigma -f $shrink -l 1 -u 1 -z 1 -u 1"
+
+[ ${transl} -eq 0 ]  && { stage0='';} || { diffeopost="trasl"; }
+[ ${rigid}  -eq 0 ]  && { stage1='';} || { diffeopost="rigid"; }
+[ ${affine} -eq 0 ]  && { stage2='';} || { diffeopost="affine"; }
+[ ${nonlin} -eq 0 ]  && { stage3='';} || { diffeopost=$( echo $diffeo | cut -d "[" -f1 );}
 
 ### === Output paths ===
 ANTs_outputs="ANTs_outputs"
@@ -65,21 +127,19 @@ name_noext="${name_noext%.nii}"      # remove .nii if present
 ANTsprefix=${ANTs_outputs}/${name_noext}_
 ANTsdiff=${ANTsprefix}"diff.nii.gz"
 ANTsinv=${ANTsprefix}"inv.nii.gz"
-singularity exec -e docker://brainlife/ants:2.2.0-1bc antsRegistration -d 3 \
-  -r [${fa_fixed},${fa_moving},1] \
-  -m mattes[${fa_fixed},${fa_moving},1,32,regular,0.25] \
-  -t affine[0.1] \
-  -c [${its},1e-6,10] \
-  -s ${sigma} \
-  -f ${shrink} \
-  -m cc[${fa_fixed},${fa_moving},1,4] \
-  -t SyN[0.2,3,0] \
-  -c [${its},1e-6,10] \
-  -s ${sigma} \
-  -f ${shrink} \
-  -o [${ANTsprefix},${ANTsdiff},${ANTsinv}] \
-  --verbose
+singularity exec -e docker://brainlife/ants:2.2.0-1bc \
+    antsRegistration \
+    -d 3 \
+    -r [${fa_fixed},${fa_moving},1] \
+    $stage0\
+    $stage1\
+    $stage2\
+    $stage3\
+    $ref_command_w \
+    -o [${ANTsprefix},${ANTsdiff},${ANTsinv}] \
+    --verbose
 
+### === Apply trasnformation to moving image using ANTs ===
   WarpField=${ANTsprefix}"1Warp.nii.gz"
   InverseWarpField=${ANTsprefix}"1InverseWarp.nii.gz"
   AffineMat=${ANTsprefix}"0GenericAffine.mat"
